version: "3"

services:
  aa_proxy:
    hostname: "AA_PROXY"
    container_name: "AA_PROXY"

    volumes:
      - ./certs:/etc/letsencrypt:z
      - ./sites:/etc/nginx/conf.d:z
      - ./logs:/var/log/dejan:z

    build:
      dockerfile: ./Dockerfile
      context: ./

    ports:
      - 80:80
      - 443:443

    env_file:
      - cloudflare.env
#    environment:
#      - CERTBOT_EMAIL=
#      - CLOUDFLARE_API_KEY=
#      - WAIT_SECONDS=
#      - DOMAIN=




